- nightly/index.php
- nightly/v2.x/index.php
- software/ompi/nav.inc
- software/ompi/v2.x/timeline-graph.php
- software/ompi/versions/timeline.php
> initial changes for fork of v2.x

- doc/v1.10/man3/MPI_Barrier.3.php
- doc/v1.10/man3/MPI_Ibarrier.3.php
- doc/v1.8/man3/MPI_Barrier.3.php
- doc/v1.8/man3/MPI_Ibarrier.3.php
Thanks to Harald Servat for reporting this
> Fix man pages for MPI_Ibarrier in v1.8 and v1.10

- faq/java.inc
Updates to the FAQ for recent changes to the Java bindings.
Signed-off-by: Nathaniel Graham <ngraham@lanl.gov>
@hppritcha  @jsquyres
> Java FAQ update

- faq/tm.inc
Add an entry about how to make sure one is configuring/building
Open MPI with Torque/PBSpro support.  Add an example of how
to determine from ompi_info whether or not an installed
Open MPI includes this support.  Qualify statement in first
entry in the FAQ to indicate there's more than magic involved
in getting Open MPI to work with Torque/PBSpro.
@jsquyres double check, etc.
> faq:update Torque/PBSpro faq

- faq/java.inc
Added documentation for persistent problems involving the java
bindings and psm/psm2.  Problems involving psm/psm2 have arisen
on multiple occasions, this will hopefully advise users on
how to fix or get help with errors they encounter.
Signed-off-by: Nathaniel Graham <ngraham@lanl.gov>
@hppritcha can you take a look?
> Updated the Java FAQ to include known limitations section

- community/mirrors/mirrors.txt
Delete some stale mirrors, add one more new mirror.
> mirrors: update mirrors listing

- source/nav.inc
> Remove link to searchable source tree; it no longer exists

- faq/debugging.inc
Signed-off-by: Kristjan Onu <kristjan.onu@canada.ca>
> Correct spelling in debugging FAQ

- faq/debugging.inc
Signed-off-by: Kristjan Onu <kristjan.onu@canada.ca>
> Correct grammar in debugging FAQ

- projects/hwloc/nav.inc
@jsquyres @ggouaillardet I stole the noindex code from OMPI to apply it to hwloc doc < 1.11. Seems to work on my local web server.
And by the way, I am changing hwloc's meta_keywords.
> update hwloc headers

- papers/index.php
- papers/sc-2016-pmix/data.inc
- papers/sc-2016-pmix/index.php
- papers/sc-2017-pmix/data.inc
- papers/sc-2017-pmix/index.php
- papers/sc-2017/data.inc
- papers/sc-2017/index.php
This PR adds the slides for the OMPI BoF. It also adds the slides for 2016 PMIx BoF, and a placeholder for 2017 BoF. The 2017 PMIx BOF is not yet referenced from the main paper page.
> Add SC'17 slides.

- index.php
> Remove some outdated news items

- index.php
> Minor news tweaks

- papers/aosa-vol-2/data.inc
> papers/aosa: Fix typo in book name

- faq/openfabrics.inc
Fixes #28.  Thanks to @chrissamuel for noticing; sorry it took us so long to fix it!
> faq/openfabrics: clarify XRC support

- community/lists/ompi.php
> ompi lists: add ompi-packagers list

- community/lists/ompi.inc
> ompi lists: add nav link for ompi-packagers archives

- includes/header.inc
- papers/index.php
> More miscellaneous updates for the presentations page

- papers/index.php
> papers: one more minor update

- papers/pdp-2010/data.inc
> Update for hwloc paper page

- papers/pdp-2010/data.inc
> papers/pdp-2010: was actually presented in Pisa, Italy

- index.php
> index.php: remove old news

- software/ompi/v3.1/version.inc
> ompi: post Open MPI 3.1.1rc1

- nightly/v4.0.x/index.php
> ompi: v4.0.x index.php fixes

- faq/openfabrics.inc
Thanks to @mherkazandjian for pointing out the stale link.
> openfabrics: update URL

- software/ompi/v2.1/version.inc
> Push v2.1.4rc1.

- index.php
- software/ompi/v2.1/timeline-graph.php
- software/ompi/v2.1/version.inc
So long v2.1.x series; we loved thee!
> Release v2.1.4

- software/ompi/v3.1/version.inc
> ompi: release 3.1.2rc1

- software/ompi/v2.1/version.inc
> Looks like we need v2.1.5 after all.  Bummer!

- software/ompi/v2.1/timeline-graph.php
> Fix minor typo in 2.1.x timeline graph

- sitewide_notice.inc
```
___
_,.--""```___```""--.,_
.-'_,.--""```   ```""--.,_'-.
.'.-'  _,     _   _     ,_  '-.'.
/ / .-'` /     \'-'/     \ `'-. \ \
/ / /    |      |   |      |    \ \ \
; ; ;      \_  _/     \_  _/      ; ; ;
| | |         ``         ``         | | |
| | |                               | | |
; ; ;    .-.   .-.   .-.   .-.    ; ; ;
\ \ \  (   '.'   \ /   '.'   )  / / /
\ \ '-.;         V         ;.-' / /
'.'-._ `                 ` _.-'.'
'-._`'--..,,,___,,,..--'`_.-'
`'--..,,,___,,,..--'`
```
> sitewide_notice: lists.open-mpi.org is down

- projects/hwloc/index.php
> hwloc: rc2 announces delivered out of order

- sitewide_notice.inc
> sitewide_notice: fix typo

- source/building.php
- source/git.php
Also a few other minor text updates.
> building.php: minor updates for the autotools table

- community/help/index.php
- community/lists/ompi.php
> The mailing list has a 150 KB per-message limit.

- software/ompi/v4.0/version.inc
> Fixing v4.0.0rc2 prerelease array.

- faq/running.inc
> faq/running: remove extraneous comment

- software/ompi/v4.0/timeline-graph.php
- software/ompi/v4.0/version.inc
Can one of you please review AND merge this? 
I'll be AFK until this weekend.
> Rolling v4.0.0rc3

- software/ompi/v3.0/version.inc
> Post 3.0.3rc1

- software/ompi/v3.1/version.inc
> Post 3.1.3rc1

- software/ompi/v3.0/version.inc
> ompi: Post 3.0.3rc2

- software/ompi/v3.1/version.inc
> ompi: Post 3.1.3rc2

- sc18/index.php
> Add sc18/ directory + redirect

- software/ompi/major-changes.php
> One more fix for "legacy" -> "removed"

- index.php
- nightly/index.php
- software/ompi/current/version.inc
- software/ompi/v4.0/timeline-graph.php
- software/ompi/v4.0/version.inc
> Updating Website for v4.0.0 release.

- software/ompi/nav.inc
> Updating the nav file to set v4.0.0 as Current

- index.php
> Fixing missing comma in news entry

- papers/index.php
- papers/sc-2018/data.inc
- papers/sc-2018/index.php
> sc18: first cut of Open MPI BOF slides

- software/ompi/v2.1/version.inc
> Release v2.1.6rc1

- community/help/index.php
Make the instructions more explicit, and suggest posting to a Github
Gist and/or Pastebin.
Also remove some super stale information about Myrinet.
> Update the help message: post to github gist/pastebin

- faq/general.inc
Just some typo and prose style fixes for the General FAQ section.
> Fix typos and styling in faq/general.inc

- faq/developers.inc
> Fix broken video link in Developers FAQ section

- faq/tuning.inc
> faq/tuning: properly escape some quotes

- faq/aix.inc
> Typo fixes for faq/aix.inc

- software/ompi/major-changes.php
- Change "--" to real em-dashes
- Fix a doubled "see see"
- Fix "incompatibilite" misspelling
- Style hwloc and libevent in fixed-width everywhere
- Add a missing closing "?>" to the last PHP code section
> Typo and style fixes for major-changes.php

- source/index.php
* Removes a duplicated "Advantage"/"Disadvantage" paragraph.
* Fixes some grammar issues
* Replaces "--" with a real em dash
> Typo and style fixes for source/index.php

- about/members/index.php
- faq/openfabrics.inc
- faq/tcp.inc
- faq/vampirtrace.inc
- includes/header.inc
> Fix PHP 7 warnings

- 404.php
- includes/css.inc
- includes/footer.inc
- includes/header.inc
- includes/http_header.inc
No semantic or behavioral changes; this is just code formatting.
> Use lower-case HTML identifiers consistently

- includes/faq_engine.inc
Fixes #159.
Simplifies the regexes while we're at it.
> Fix up regexes for FAQ strong/em/code markup

- faq/buildcuda.inc
- Using standard/example paths to avoid ambiguity
> Env vars with $ prefix were ignored. Using standard paths instead

- faq/categories.inc
> FAQ: Put ancient networks at the bottom of the list

- index.php
- software/ompi/v2.1/timeline-graph.php
- software/ompi/v2.1/version.inc
> v2.1.6 release

- faq/categories.inc
- faq/opa.inc
- faq/running.inc
- Add overall FAQ entry in Omni-Path
- Per Jeff's request in Issue https://github.com/open-mpi/ompi/issues/6256
add note on Multi-rail and Multi-HFI support in PSM2.
Signed-off-by: Aravind Gopalakrishnan <Aravind.Gopalakrishnan@intel.com>
> Add tuning section for Omni-Path devices

- faq/ft.inc
Signed-off-by: George Bosilca <bosilca@icl.utk.edu>
> Update the FT section.

- faq/tcp.inc
Signed-off-by: George Bosilca <bosilca@icl.utk.edu>
> Fix the link to the IEEE routing paper.

- software/ompi/v4.0/version.inc
> add 4.0.1rc1 prerelease

- doc/nav.inc
Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>
> doc: do not index Open MPI (retired) v2.0 man pages

- software/ompi/v4.0/version.inc
> add 4.0.1rc2 prerelease

- software/ompi/v4.0/version.inc
> v4.0.1rc2- try again

- software/ompi/v4.0/version.inc
> another try

- software/ompi/v4.0/version.inc
> another try at 4.0.1rc2

- software/ompi/v4.0/version.inc
> add link to v4.0.1rc1 back

- software/ompi/v4.0/version.inc
> ompi: roll to v4.0.1rc3

- software/ompi/v3.0/version.inc
> Post v3.0.4rc1

- software/ompi/v3.1/version.inc
> Post v3.1.4rc1 release

- index.php
- software/ompi/v4.0/timeline-graph.php
- software/ompi/v4.0/version.inc
> OMPI: updates for v4.0.1 release

- .github/CONTRIBUTING.md
Make a CONTRIBUTING.md file here so that contributors can see our
process.  I started with the CONTRIBUTING.md from Open MPI and tweaked
it to be a bit more appropriate for ompi-www.
> .github/CONTRIBUTING.md: First!

- video/internals.inc
> video/internals: Add disclaimer that these videos were made in 2012

- faq/building.inc
> faq/building: fix minor typos

- faq/openfabrics.inc
Add information about IB SL for UCX PML
Fixes https://github.com/open-mpi/ompi/issues/6794
> faq/openfabrics: add info about IB SL for UCX PML

- faq/openfabrics.inc
> faq/openfabrics: Fix unterminated answer

- projects/hwloc/index.php
> hwloc: add news about 2.1rc1

- software/ompi/v4.0/timeline-graph.php
- software/ompi/v4.0/version.inc
> Updating timeilne for v4.0.2rc3

- sc19/index.php
> Add first version of sc19 page: Google form iframe

- index.php
> Announcing Open MPI v4.0.2

- faq/openfabrics.inc
> faq/openfabrics: fix sentence about openib btl being deprecated

- index.php
> Fix typo in index.php

- software/ompi/v3.0/version.inc
- software/ompi/v3.1/version.inc
> Release 3.0.5rc1 and 3.1.5rc1

- sc19/index.php
> Update SC19 link to point to feedback form

- index.php
- software/ompi/v3.0/version.inc
- software/ompi/v3.1/version.inc
> release v3.0.5 and 3.1.5

- papers/index.php
- papers/sc-2019/data.inc
- papers/sc-2019/index.php
> Add SC19 Open MPI BOF slides

- doc/index.php
Thanks to @mwheinz for pointing this out.
> doc: don't say v2.1.x is still supported

- projects/hwloc/index.php
- projects/hwloc/nav.inc
> hwloc: add a link to the XML topology database

- index.php
- software/ompi/v3.0/version.inc
- software/ompi/v3.1/version.inc
> Release v3.0.6rc1 and 3.1.6rc1

- software/ompi/v4.0/timeline-graph.php
- software/ompi/v4.0/version.inc
> Updating website for v4.0.3rc3

- software/ompi/v3.0/version.inc
- software/ompi/v3.1/version.inc
> Release v3.0.6rc2 and 3.1.6rc2

- software/ompi/v4.0/timeline-graph.php
- software/ompi/v4.0/version.inc
> Updating timeline for v4.0.3rc4

- index.php
- software/ompi/v4.0/timeline-graph.php
- software/ompi/v4.0/version.inc
> Updating for v4.0.3 release

- software/ompi/v4.0/timeline-graph.php
- software/ompi/v4.0/version.inc
> OMPI v4.0.4rc1 updates

- source/building.php
> src/building.php: add notes about Pandoc

- source/building.php
> source/building.php: Fix some HTML

- software/ompi/v4.0/timeline-graph.php
- software/ompi/v4.0/version.inc
> update for 4.0.4rc2

- software/ompi/v4.0/timeline-graph.php
- software/ompi/v4.0/version.inc
> Updating for v4.0.4rc3

- nightly/index.php
- nightly/v4.1.x/index.php
> nightly: Add 4.1.x release series

- index.php
- software/ompi/v4.0/timeline-graph.php
- software/ompi/v4.0/version.inc
> OMPI 4.0.4 release

- faq/openfabrics.inc
> OpenFabrics FAQ: iWARP and RoCE updates

- faq/openfabrics.inc
> More updates to the openfabrics FAQ entries.

- video/general.inc
> Add slides + video for "ABCs of Open MPI" part 2.

- software/ompi/v4.0/timeline-graph.php
- software/ompi/v4.0/version.inc
> Updating for v4.0.5rc1

- software/ompi/v4.0/timeline-graph.php
- software/ompi/v4.0/version.inc
> Updating timeline for v4.0.5rc2

- index.php
- software/ompi/v4.0/timeline-graph.php
- software/ompi/v4.0/version.inc
> OMPI:updates for 4.0.5 release

- index.php
> mainpage: change hwloc news from 2.1 to 2.3

- software/ompi/v4.1/version.inc
> Release Open MPI 4.1.0rc2

- software/ompi/v4.1/version.inc
> Release 4.1.0rc3

- software/ompi/v4.1/version.inc
> Open MPI v4.1.0rc4

- software/ompi/v4.1/version.inc
Signed-off-by: Raghu Raja <craghun@amazon.com>
> Open MPI v4.1.0rc5

- software/ompi/v4.0/timeline-graph.php
- software/ompi/v4.0/version.inc
> Updating websight for v4.0.6rc1

- software/ompi/v4.0/version.inc
> oops Type-o in version.inc for v4.0.6rc1

- faq/slurm.inc
> Simpler Slurm recomendation.

- software/ompi/v4.0/timeline-graph.php
- software/ompi/v4.0/version.inc
Tarball: https://jenkins.open-mpi.org/jenkins/job/open-mpi.dist.create-tarball/355/
> Updating timeline for v4.0.6rc2 - Assuming Feb 16

- nightly/index.php
- nightly/v5.0.x/index.php
This commit creates the usual nightly/v5.0.x for the new
v5.0.x release branch, with the usual development
warning.
> Create a nightly/v5.0.x place for nightly tarballs.

- software/ompi/v4.1/timeline-graph.php
- software/ompi/v4.1/version.inc
Signed-off-by: Raghu Raja <craghun@amazon.com>
> Updates for v4.1.1rc2

- software/ompi/v4.1/timeline-graph.php
- software/ompi/v4.1/version.inc
> v4.1: Release 4.1.1rc3

- software/ompi/v4.1/timeline-graph.php
- software/ompi/v4.1/version.inc
> ompi: Release Open MPI 4.1.1rc4

- index.php
> Fix the link to the v4.1.1 announcement email

- software/ompi/v4.0/timeline-graph.php
- software/ompi/v4.0/version.inc
> updates for OMPI v4.0.6rc4

- software/ompi/v4.0/timeline-graph.php
- software/ompi/v4.0/version.inc
we'll do the link to the release email separately
> openmpi: timeline and version updates for v406

- index.php
> open mpi: update announce section for 4.0.6

- software/ompi/v4.1/timeline-graph.php
- software/ompi/v4.1/version.inc
> Publish Open MPI 4.1.2rc1

- doc/index.php
- doc/nav.inc
> Add v5.0 navs for docs

- software/ompi/v4.0/timeline-graph.php
- software/ompi/v4.0/version.inc
> OMPI: timeline updates for v4.0.7rc2

- software/ompi/v4.0/timeline-graph.php
- software/ompi/v4.0/version.inc
> ompi v4.0.7 timeline and version update

- index.php
> ompi: update index for 4.0.7 release announce

- software/ompi/v4.1/timeline-graph.php
- software/ompi/v4.1/version.inc
> Post 4.1.2rc3

- papers/index.php
> papers: add missing entry for euro-pvmmpi-2005-fortran

- projects/hwloc/doc/index.php
> hwloc/doc: fix the links to 2.7.0 docs

- faq/building.inc
Some of these may be dated and could be removed.
> Update faq with LSF build dependencies.

- faq/runcuda.inc
- Provide example of how to select CUDA device based on local_rank
- Add caveat with cudaDeviceReset before MPI_Finalize
Patch provided by @jirikraus
> Add FAQ on cuda device selection / reset

- software/ompi/v4.1/timeline-graph.php
- software/ompi/v4.1/version.inc
> Post 4.1.3rc1

- faq/supported-systems.inc
> faq: update Platform -> IBM

- software/ompi/v4.1/timeline-graph.php
- software/ompi/v4.1/version.inc
> Release Open MPI 4.1.3rc2

- software/ompi/v5.0/timeline-graph.php
- software/ompi/v5.0/version.inc
- Update the version and timeline for rc4.
> OMPI v5.0.0rc4 updates.

- software/ompi/v5.0/timeline-graph.php
- software/ompi/v5.0/version.inc
> OMPI v5.0.0rc5 updates.

- software/ompi/v5.0/timeline-graph.php
- software/ompi/v5.0/version.inc
> OMPI v5.0.0rc6 updates.

- software/ompi/v4.1/timeline-graph.php
- software/ompi/v4.1/version.inc
> Release 4.1.4rc1 into the wild

- software/ompi/v5.0/version.inc
> OMPI v5.0.0rc7 updates.

- index.php
> Fix 4.1.4 announcement URL

- software/ompi/v5.0/timeline-graph.php
- software/ompi/v5.0/version.inc
> OMPI v5.0.0rc9 updates.

- software/ompi/v4.1/timeline-graph.php
- software/ompi/v4.1/version.inc
> Post 4.1.5rc1

- software/ompi/v4.1/timeline-graph.php
- software/ompi/v4.1/version.inc
> Release OMPI 4.1.5rc2

- doc/v4.1/man3/MPI_Gather.3.php
> Fix accidentally-duplicated text in v4.1 MPI_Gather

- software/ompi/v5.0/timeline-graph.php
- software/ompi/v5.0/version.inc
Tarballs are available https://jenkins.open-mpi.org/jenkins/job/open-mpi.dist.create-tarball/424/
> Add 5.0.2rc2 references

- software/ompi/v5.0/timeline-graph.php
- software/ompi/v5.0/version.inc
Remove RC and add v5.0.2 reference
> Update 5.0.2 references

- index.php
Only keep the latest supported releases
> remove old releases from main page

- software/ompi/v5.0/timeline-graph.php
- software/ompi/v5.0/version.inc
Tarball is being built here https://jenkins.open-mpi.org/jenkins/job/open-mpi.dist.create-tarball/428/
> Update website for Open MPI v5.0.4rc1

- software/ompi/v5.0/timeline-graph.php
- software/ompi/v5.0/version.inc
> Update website for Open MPI v5.0.5
