- faq/building.inc
This is the fix to  #818, https://github.com/open-mpi/ompi/issues/818
> Added an new item how to link intel statically

- faq/developers.inc
Should redirect to https://www.open-mpi.org/source/git.php.
> faq: fix link to obtaining source

- community/lists/functions.inc
Fix list mailto: links to correctly be <name>@lists.open-mpi.org
> Fix list mailto: links to correctly be <name>@lists.open-mpi.org

- faq/java.inc
Minor changes to the Java FAQ to fix typos as pointed
out by Jeff.
Signed-off-by: Nathaniel Graham <ngraham@lanl.gov>
@jsquyres I fixed the capitalization problem and noticed
that the other sentences only had 1 space instead of two
after a period.  I am not sure if "exist" is any better than
"are currently", but it looked better to me.  I did not say
anything about the version number that fixes the signal
hijacking in psm because there are still other problems
that cause, in my experience, more frequent crashes than
the signal hijacking problem did and I did not want to get
into too much detail about signal hijacking in a FAQ.
My intent is to update this section once a fix is implemented,
and at that point mention the version number that fixes the
problems I have been seeing.
> Fix capitalization and spacing typos in Java FAQ

- source/building.php
There is currently debate occurring about the minimum required tools
versions for developer builds (vs. the versions required for nightly
snapshot / official release builds).  While this debate is ongoing in
the developer community, at least clarify the statement on the web
page about the current status -- even if this status changes as a
result of the ongoing conversation.
> building.php: update statement about min required Autotools versions

- community/license.php
We've always distributed Open MPI under the 3-clause BSD license and
showed the right text of the license on the web site; we just had the
link accidentally pointing to 2-clause BSD license on opensource.org.
> licence: fix link to point to 3-clause BSD license

- faq/runcuda.inc
Patches to handle GPU buffers in PSM2 MTL went in with upstream PR
(https://github.com/open-mpi/ompi/pull/4143). Patches against master
branch have also been subsequently cherry-picked to release branches
2.x, 3.0.x and 3.1.x.
Updating FAQ entries here to reflect the changes.
Signed-off-by: Aravind Gopalakrishnan <Aravind.Gopalakrishnan@intel.com>
> Update FAQ on CUDA-aware Open MPI to include PSM2 support

- .htaccess
Change the rewrite rule that was intended to redirect visitors
from open-mpi.org to www.open-mpi.org to be pickier about the
origin URL, so that it only redirects from open-mpi.org and not
from other URLs (such as aws.open-mpi.org).  This allows the
tree to be usable from home directories on aws.open-mpi.org,
which is great for testing before pushing to prod.
> htaccess: stop always adding www to URL

- 404.php
The 404 error handler redirected to 404.php (the error handler doc),
which displayed the right thing but didn't actually cause a 404
to clients.  This caused some failures with wget which were very
confusing.  Fix that behavior by removing the redirect and
greatly simplifying the error document because of $topdir
computation problems described in the 404.php file.
Fixes #45.
> Fix 404 Error Handler

- community/lists/ompi-packagers/index.php
Make a subdirectory named ompi-packagers so that it prints a link out
to the mail-archive.com archive of this list.
> ompi-packagers: make it print link to mail-archive

- papers/index.php
Over the past several years, many of the academic members of the Open
MPI community have not posted their papers to this web site.  In the
2018-03 OMPI developer meeting, we decided to take the majority of
content on this page down and rely on normal academic paper archiving
for access to the old papers.
Project-level presentations (e.g., SC BOF slides) sare kept here, as
are a small number of papers that detail the inner workings of Open
MPI itself.
> papers: remove many of the papers

- software/ompi/v3.0/version.inc
In the tarball move to S3, looks like I accidently "unreleased"
Open MPI 3.0.2rc1.  Add it to the release list.
> Re-release Open MPI 3.0.2rc1

- includes/downloads.inc
We were trying to use the default provider (which was looking
for creds somewhere) rather than no provider when on mirror
sites, which broke the download list.  If we're not on a host
that should have creds (currently, *.open-mpi.org hosts), just
use anon access.
> Use unauthenticated S3 access for mirrors

- doc/index.php
When we overhauled how version tracking happens, I broke the release
list in the Documentation page.  We were already inconsistent in
release series naming, so make everything uniform.
> Fix version list on Open MPI Documentation page

- software/mtt/current/version.inc
We have no version.inc for the MTT v3.0 series because there are no
downloadable tarballs.
FYI @petergottesman
> MTT: There is no version.inc

- faq/tcp.inc
- set send and receive buffers size to zero
- warn about the currently non working multiple links option
Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>
> faq/tcp: Add entries related to TCP perf

- faq/all.inc
- faq/categories.inc
- faq/mpi-apps.inc
- faq/mpi-removed.inc
This echoes the language in the MPI-3.0 spec ("removed interfaces").
> FAQ: Renamed "legacy" to "removed"

- faq/mpi-removed.inc
In one of the FAQs in mpi-removed.inc, it refers to the compatibility flag as `--enable-mpi-compatibility` instead of `--enable-mpi1-compatibility`. Is that a typo? It [didn't work for me](https://github.com/Homebrew/homebrew-core/pull/34973#issuecomment-446274306) when I tried it, where `--enable-mpi1-compatibility` did.
> faq/mpi-removed: fix --enable-mpi1-compatibility flag typo

- faq/building.inc
Just a few typo and style fixes for faq/building.inc.
Fixes some typos and spelling errors.
Renders file names more consistently in fixed width font.
> Fix typos and styling in faq/building.inc

- faq/supported-systems.inc
Minor typo and prose style fixes for the Supported Systems FAQ section.
> Fix typos and styling in faq/supported-systems.inc

- faq/sge.inc
Fixes a couple typos and makes styling more consistent.
Uses double-quotes throughout instead of single quotes for parameter names.
> Fix typos and style in faq/sge.inc

- faq/large-clusters.inc
The style changes here are mostly:
* Using fixed-width font for literal code and program names
* Using em-dashes instead of hyphens where appropriate
> Typo and style fixes for faq/large-clusters.inc

- faq/tuning.inc
In other pages in the FAQs, quotes were not used in conjunction with fixed-width `<code>` formatting for literal parameter names and code snippets, so I have removed the extra quotes on this page to be consistent.
> Typo and style fixes in faq/tuning.inc

- doc/index.php
On the current website, this is rendering as:
Note the extra "strong>" showing up at the end of the line.
This PR cleans that up.
> Remove busted "strong>" tag dropping in doc/index.php

- faq/bug-functions.inc
- faq/openfabrics.inc
It looks like the current Open MPI issue tracker has been migrated from the old Trac system to GitHub issues, so the FAQ `ompi_bug()` function should probably point to GitHub issues.
This PR changes `ompi_bug()` to point to GitHub issues, and replaces the single usage of it for Trac bug 1224 with a hardcoded URL to the old Trac system, since it doesn't seem like that particular bug got migrated over (probably because it was closed before the migration happened).
> Migrate ompi_bug() function to GitHub Issues

- faq/myrinet.inc
Basic typo fixes.
Plus, I elided the "named" from "MCA parameter named [foo]" because that's the usage in all the other FAQ sections I've seen so far.
> Typo fixes for faq/myrinet.inc

- faq/perftools.inc
* Minor typo and style fixes.
* Uses American-style "-ize" instead of UK-style "-ise", since that seems to be dominant within the repo already:
```
$ grep --exclude 'community/lists/*' -r standardize * | wc -l 
13
$ grep --exclude 'community/lists/*' -r standardise * | wc -l  
1
```
* Updates the link for Allinea DDT, which is now called Arm DDT and has a different URL.
> Typo and style fixes for faq/perftools.inc

- faq/java.inc
This one's more than just typo/style fixes. Also:
* I have added a live link to the referenced "Design and implementation of Java bindings in Open MPI" paper.
* Some of the examples used a mix of `my-XXX` and `your-XXX`, both of which referred to MPI user code. I have changed them to just use `your-XXX` for consistency of perspective.
* One of the shell code examples just used "`foo`" and "`bar`" as path placeholders. I've replaced them with the more descriptive `/path/to/jdk/bindir` and `/path/to/jdk/headers`, which I think are more readable, and suggest using absolute paths.
> faq/java: Typo/style fixes, wording consistency improvements, live paper link

- faq/vampirtrace.inc
Minor typo and style fixes.
I also removed the qualifying phrase "(in Open MPI v1.3 and later)" because the `$vampir_is_gone` section already takes care of explaining which versions these FAQs are applicable to.
> Typo and style fixes for faq/vampirtrace.inc

- faq/buildcuda.inc
* Minor style fixes: use Oxford commas consistently and fixed-width formatting for command names.
* Note that `/usr/local` might not be the default prefix for a build.
* Fix busted closing `</geshi>` tag: it can't be `</geshi text>` or it'll be ignored.
* Use imperative "search" instead of descriptive "searches". I think it's more readable.
> Style fixes for faq/buildcuda.inc

- faq/runcuda.inc
* Style it consistently as "GPUDirect", not "GPU Direct", matching [NVIDIA's branding](https://developer.nvidia.com/gpudirect)
* Remove all "`(r)`" trademark indicators, since they're not used anywhere else on this site where "Intel" and similar trademarks occur
* Style MCA parameter names in fixed-width instead of bold
* Use "run-time" instead of "runtime", to match usage in other FAQ sections
* Minor typo fixes
* Use colons to introduce example code snippets
> Typo and style fixes for faq/runcuda.inc

- about/members/index.php
Just a replacement of a "--" with a better-looking em-dash.
> Style fix for about/members: just an em-dash fix

- performance/index.php
- Change the search name to "just performance", since the other pages that
offer a restricted search also use "just" in their search names
- Fix spelling of "familiar" and include a "with" on it
- Capitalize the list items, since that's easier on the eyes and consistent
with other lists in this website
- I think the saying is conventionally "apples to apples", plural, not "apple vs apple"
- Add a missing period at the end of one paragraph
> Style tweaks to performance/index.php

- subscribe-announce.php
The missing space is causing squashed text that looks like "...about Open MPI(i.e., confirm that..." in Chrome.
> subscribe-announce.php: just fix a missing space

- papers/aosa-vol-2/data.inc
- papers/euro-pvmmpi-2004-overview/data.inc
- papers/euro-pvmmpi-2006-hpc-protocols/data.inc
- papers/euro-pvmmpi-2007-ib/data.inc
- papers/euro-pvmmpi-2007-mtt/data.inc
- papers/ics-2004/data.inc
- papers/index.php
- papers/kicc-2007/data.inc
- papers/papers.inc
- papers/ppam-2005/data.inc
- papers/sc-2005/data.inc
- papers/sc-2006/data.inc
- papers/sc-2008/data.inc
- papers/sc-2009/data.inc
- papers/sc-2010/data.inc
The big change in this: it changes the visible `papers/*/data.inc` files to consistently *not* use a period at the end of `$overview`. This is appropriate because they are sentence fragments, not complete sentences.
Compare to how they are rendered now: despite the fact that they are (almost) all sentence fragments, some of them end with a period, and some of them don't.
This PR will make the styling in `papers/` more consistent. (The one or two that are full sentences, I still removed the period from, for visual consistency.)
This PR also:
* Fixes a bug in `papers/papers.inc` where it messes up the case for ".DOC" and forgets the upper-case ".PPTX" variant
* Tidies up the indentation and code formatting in `papers/index.php`, without changing the actual content
> Fix papers styling

- faq/sm.inc
Fixes #167.
I think this is the right replacement link for showing the sm allocation algorithm in the new GitHub history instead of the old SVN history, which is now 404.
I picked it out by looking at the revision history for `ompi/mca/btl/sm/btl_sm.c` and manually selecting a likely revision. The GitHub commit that [contains the migrated SVN r20906](https://github.com/open-mpi/ompi/commit/12ce14ec8c88a676518a70b55766bebc324db764) that was referenced in the original link doesn't look like its diff actually contains the relevant algorithm.
> faq/sm.inc: Migrate allocation algorithm link to GitHub

- faq/perftools.inc
Fixes #178.
This updates the link to point to the MPI-3.1 doco instead of the MPI-2.2 doco. The new link is live.
> Update link for the MPI standard Profiling Interface doco

- faq/perftools.inc
Fixes #179.
Updates the link for TotalView to a currently-working URL. Manual inspection of the new website sure looks like it's the same product.
> Update URL for TotalView in faq/perftools.inc

- nightly/index.php
> Fix a "previuos" typo in nightly/index.php

- source/building.php
In `source/building.php`, the current centering logic centers some of the paragraphs of prose in addition to the two tables. For readability, maybe only the tables should be centered, leaving all the prose left-justified like normal?
This PR restricts the scope of the `<CENTER>`ing so that only the tables are centered, and the middle prose paragraphs are left-justified.
> source/building: Only center the tables; not the prose

- source/building.php
* Fixes a couple spelling errors
* Renders "gfortran" in fixed-width font using `<code>`
* Replaces "--" with real em dashes
* Capitalizes the first Note at the bottom for parallelism
> Typo and style fixes for source/building.php

- faq/building.inc
- faq/categories.inc
- faq/large-clusters.inc
- faq/openfabrics.inc
- faq/running.inc
- faq/slurm.inc
- faq/supported-systems.inc
- faq/sysadmin.inc
The Slurm project is now styling their name as "Slurm" instead of the all-caps "SLURM". How about updating the Open MPI doco to match their styling?
> Re-style "SLURM" as "Slurm" to match Slurm project's current branding

- includes/header.inc
- sitewide_notice.inc
It looks like the Sitewide Notice is not actually working, due to a couple malformed `<?php` tags.
This PR fixes it.
> Fix "<?php" tags for sitewide notice

- .htaccess
These entries were placed in our live site's .htaccess file by our
hosting provider.  We may not need them any more, but I'm a bit
nervous about removing them.  So we might as well commit them (since
they've been live on the site for forever; we might as well put them
in git so that we don't accidentally overwrite them on the live
site).
> .htaccess: updates from the live site

- .htaccess
- doc-www/README.txt
- doc-www/Style-Guide.md
- doc-www/bin/grep-variants
What do you think about adding a `doc-www/` directory with documentation and tools for the `ompi-www` website itself?
The Style Guide file in this PR is based on the prevailing usage I've observed in the existing `ompi-www` code base.
> Add a website doco directory?

- software/mtt/current/version.inc
There are a couple missing variables in the MTT `version.inc` file. This causes the following PHP warnings on the MTT page:
This PR fixes them.
> Fix missing variables in MTT definitions

- software/otpo/current/version.inc
Just like #210, but for the OTPO version definitions.
> Fix missing variables in OTPO definitions

- community/contribute/nav.inc
These pages just redirect back to the main Contribute page, so
may as well remove them from the nav bar. The actual page files are
still there so no existing links will break.
> Remove "individual"/"corporate" Contribute sub-items

- includes/http_header.inc
"HPC" is one of the core topic terms for what Open MPI does, right? Maybe we should add it to the site's meta keywords.
> Add HPC and "high performance computing" to meta keywords

- faq/ompio.inc
Notable things in this PR:
Big one: this will break a few anchors due to correcting spelling errors in the anchor names. (e.g. correcting `$anchor[] = "fs-parametesrs";` to `$anchor[] = "fs-parameters";`) That's probably fine, since this isn't a major page...?
Minor ones:
* I changed an unordered list to a definition list, down where it's enumerating named features under "What other features of OMPIO are available?"
* The rendering of `OMPIO [io], [fcoll], [fs], and [sharedfp] components:` may break due to #159
* Down under "The sharedfp framework provides...", I rearranged the parentheses nesting to what I think was the original intent.
* Rendering of some stuff in this paragraph will probably still be broken due to #159.
> Typo and style fixes for faq/ompio.inc

- faq/openfabrics.inc
Fixes #174.
This PR updates the FAQ's link to the documentation for the Linux PAM `limits` module. After some Googling, I think the new URL is correct.
> Update link to the Linux PAM limits module

- nightly/index.php
- 4.0.x: currently recomended for all users
- 3.1.x, 3.0.x, 2.1.x: bug fix only mode
- 2.0.x: unlikely to be updated
Also remove verbiage about odd/even version number philosophy; we
don't do that any more.
> nightly: update nightly listing

- faq/openfabrics.inc
Please review and merge this commit if you find it acceptable or let me know what how it should be changed.
> FAQs for github issue #6517

- includes/downloads.inc
For reasons that escape me, I disabled authenticating against our
S3 bucket for hosts that weren't aws.open-mpi.org or hostgator.
The creds have to come from somewhere else either way, so I was
just making it harder to do things like move www.open-mpi.org
from HostGator to AWS.
Now, we will always use the default auth provider (which will
use instance roles, environment variables, .aws/credentials/, etc.)
everywhere but HostGator, which needs the special config to
get the creds file correctly.
> Use default auth for S3 access on most hosts

- includes/downloads.inc
As part of #255, display sha256 hashes of downloads, if they were
published.
> downloads: Add (optional) SHA256 hash

- faq/building.inc
Document a problem that can occur on modern MacOS systems with
Homebrew, and add information about the bundled vs. system-installed
hwloc and Libevent packages.
> faq/building: Add info about hwloc/libevent

- software/hwloc/nightly/index.php
Those snapshots are built by Jenkins during nightly extended tests.
They include Windows zipballs, PDF/HTML documentation, etc.
Former nightly pages for v1.11, v2.0 and master still exist
and are updated, we'll remove them in a couple weeks/months
unless something bad happens.
> hwloc: point to ci.inria.fr/hwloc for nightly snapshots

- index.php
Due to the fast release of 3.0.5 and 3.1.5 in time for the SC'19
BOF, an announce email wasn't sent at time of release.  Now that
we have cleaned up from that delay, include the announce email
link in the front page boxes.
> Update release box URLs

- faq/runcuda.inc
INTERNAL: STL-59958
Adds a new page to the CUDA-aware FAQ pages providing information about
writing Open-MPI applications that are CUDA-aware.
Signed-off-by: Michael Heinz <michael.william.heinz@gmail.com>
> REF7240 Update CUDA/Omnipath FAQ docs

- source/git.php
- source/index.php
> Add a little text for git submodules

- nightly/index.php
No need to list the v2.1.x nightly tarballs in the "Prior stable
release series" list -- it's even older than that.
> nightly: v2.1.x has been retired for quite a while

- faq/debugging.inc
If the sleep flag variable 'i' is not declared as volatile, most compilers will
not allocate a memory address, meaning that it cannot be set in gdb using
'set var i = 7' as suggested.
> add volatile qualifier to sleep flag for gdb attach to process

- source/building.php
Bring over documentation infrastructure changes introduced in https://github.com/open-mpi/ompi/pull/7600 to the documentation on the Open MPI website.
> Add pandoc to list of developer build dependencies for Open MPI

- faq/debugging.inc
- The `mpirun -np <n> xterm -e gdb <app>` method usually works well
on personal computers. Mention this early on, so that potential readers
wanting to debug on their own machine are not discouraged of trying it
by the long section below.
- [`tmpi`](https://github.com/Azrael3000/tmpi) is a small script that uses the terminal multiplexer
`tmux` to launch separate instances of an OpenMPI program. It can be used to debug MPI applications by launching separate debugger
processes for each rank, and has the advantage of synchronizing
keyboard input to all debugger instances. Add a mention of this nice script in the debugging section of the
FAQ.
- Also, a small markup fix
> Debugging FAQ: add mention of 'tmpi' and don't scare off people of trying the 'xterm' method

- .github/CONTRIBUTING.md
- faq/debugging.inc
When I did #316 I read the [Wiki entry](https://github.com/open-mpi/ompi/wiki/OMPIFAQEntries) linked in the [CONTRIBUTING](https://github.com/open-mpi/ompi-www/blob/master/.github/CONTRIBUTING.md) document and did not check my changes (I did not know it was as easy as `php -S localhost:8000`), and it turns out the wiki entry is not up to date, so the Debugging FAQ does not work at the moment because of the call to `aurchin_click`.
- Add an example of local testing in CONTRIBUTING ([should work with PHP >=5.4](https://www.php.net/manual/en/features.commandline.webserver.php))
- Remove the call to `aurchin_click` that makes the page fail.
@jsquyres
> Don't use `aurchin_click`

- faq/slurm.inc
Remove notes about srun -A/srun -B the meaning of options changed and
the one mentioned here is really ancient.
Add a not about srun begin prefered instead of mpirun in sbatch/salloc.
Remove notes about issues in old versions (over 6 yers old).
Signed-of-by: Marcin Stolarek <cinek@schedmd.com>
> Update Slurm FAQ

- robots.txt
As of Jan 2021, some `www.open-mpi.org/~jsquyres/*` URLs show up in
Google searches.  This is not desirable, because they get confused
with the real web site.  So disallow all crawlers from indexing any
`~username` URLs.  It's not 100% clear if `~*` wildcard matching works
in a robots.txt, so throw in a handful of actual usernames that we
want to block, just to be sure.
> robots.txt: disallow indexing user dirs

- includes/header.inc
- software/ompi/versions/index.php
We used to download README from github and slurp out the section that
we wanted to show.  With the conversion to README.md, this is a little
more difficult.  So instead, just redirect out to the proper
subsection in README.md at github.
> Update to point to github README.md

- .htaccess
The specification of php56 instead of generic php was a holdover
from the HostGator timeframe.  When we recently removed php56,
that broke rendering of latest_snapshot.txt.
> Fix latest_snapshot.txt rendering

- software/ompi/v4.1/timeline-graph.php
I must have cut-n-pasted the entry for 4.1.2rc1 from 4.1.1 and
not updated it, then copied it again.  Thanks to Kawashima
Takahiro for pointing out the mistake.
> Fix verion typo in 4.1 timeline.

- index.php
- software/ompi/v4.1/timeline-graph.php
- software/ompi/v4.1/version.inc
I forgot to add the three version files to actually release in the
previous commit.  Sigh.
> Really release Open MPI 4.1.3

- software/ompi/v5.0/version.inc
Otherwise it won't show up in the website.
> Bug: Don't put 'v' in the releases array.

- .github/workflows/pr-checks.yaml
Move the git commit checkers to GitHub Actions, following the trend of the other Open MPI repositories.
> Add GitHub Actions for git commit checks

- software/ompi/v5.0/timeline-graph.php
- software/ompi/v5.0/version.inc
Also include a missing rc7 update to the timeline. I forgot to `git add` that file last go around.
> OMPI v5.0.0rc8 updates.

- software/ompi/v5.0/index.php
We don't have a NEWS file any more.  Instead, link to the v.5.0.x on docs.open-mpi.org.
Thanks to @BenWibking for the heads up that the link was broken.
Refs: https://github.com/open-mpi/ompi/issues/11572
> Fix hyperlink to v5.0.x NEWS file

- source/building.php
Add links to docs.open-mpi.org for main and >= v5.0.0.
Also remove some leftover Pandoc text.  Long live Sphinx!
> source/building.php: updates for >= v5.0.0

- projects/hwloc/index.php
The latest_snapshot link still isn't well known.
> hwloc: change what's bold or not in the mainpage download summary

- .htaccess
- projects/hwloc/index.php
- software/hwloc/current/downloads/latest_release.txt
- software/hwloc/v2.9/downloads/latest_release.txt
Some people want the latest release version number, not including release candidates.
Refs Homebrew/homebrew-core#151735
> hwloc: add latest_release.txt near latest_snapshop.txt

- includes/header.inc
- software/ompi/major-changes.php
- software/ompi/v5.0/index.php
* Link to docs.open-mpi.org page about version information instead of github
* add a missing <hr> in major-changes.php
> docs: two minor tweaks:

- includes/faq_engine.inc
Put a specific notice in the FAQ that it is intended for Open MPI <=v4.x; anyone looking for >=v5.x docs should go to docs.open-mpi.org.
> FAQ: Add link to >=v5.x docs.open-mpi.org

- community/lists/hwloc.php
- community/lists/mtt.php
- community/lists/ompi.php
- doc/index.php
See individual commit messages for details
> Misc docs updates

- community/lists/functions.inc
- community/lists/hwloc.php
- community/lists/mtt.php
- community/lists/ompi.php
In January of 2025, we migrated all the mailing lists away from GNU Mailman to Google Groups.  We also consolidated and removed a few lists.
Update the mailing list pages to reflect the most current / correct information about the Open MPI, hwloc, and MTT mailing lists.
> Update mailing list links for Google Groups
